/*
* generated by Xtext
*/
package org.example.domainmodel;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ExtendedStandaloneSetup extends ExtendedStandaloneSetupGenerated{

	public static void doSetup() {
		new ExtendedStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

