/*
 * generated by Xtext
 */
package org.example.domainmodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExtendedRuntimeModule extends org.example.domainmodel.AbstractExtendedRuntimeModule {

}
