/**
 * generated by Xtext
 */
package org.example.domainmodel.validation;

import org.example.domainmodel.validation.AbstractExtendedValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExtendedValidator extends AbstractExtendedValidator {
}
