
DROP TABLE Noticia;

CREATE TABLE Noticia (
    noticiaId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR (100),
    resumo VARCHAR (250),
    conteudo VARCHAR (1000),
    imagem BLOB,
    data DATE,
    imagemContentType VARCHAR (30)
);


DROP TABLE AreaDePesquisa;

CREATE TABLE AreaDePesquisa (
    areaDePesquisaId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR (100),
    descricao VARCHAR (255)
);


DROP TABLE ProjetoDePesquisa;

CREATE TABLE ProjetoDePesquisa (
    projetoDePesquisaId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR (100),
    descricao VARCHAR (255),
    dataInicio DATE,
    dataFim DATE,
    apoio BIGINT,
    area BIGINT
);


DROP TABLE Suporte;

CREATE TABLE Suporte (
    suporteId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    agencia VARCHAR (100),
    icone BLOB,
    iconeContentType VARCHAR (30)
);


DROP TABLE Link;

CREATE TABLE Link (
    linkId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR (100),
    url VARCHAR (255)
);


DROP TABLE Publicacao;

CREATE TABLE Publicacao (
    publicacaoId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    autores VARCHAR (255),
    local VARCHAR (255),
    data VARCHAR (100),
    area BIGINT
);


DROP TABLE Colega;

CREATE TABLE Colega (
    colegaId BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR (35),
    homepage VARCHAR (255)
);




DROP TABLE UserContent;

CREATE TABLE UserContent (
    userContentId BIGINT GENERATED BY DEFAULT AS IDENTITY,
	entityName VARCHAR (255),
	entityId BIGINT,
    date BIGINT,
    title VARCHAR (255),
    content VARCHAR (1000),
    name VARCHAR (100),
    email VARCHAR (100)

    , approved CHAR
    
);
