/*
 * generated by Xtext
 */
package org.example.domainmodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.example.domainmodel.ui.internal.ExtendedActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExtendedExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExtendedActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExtendedActivator.getInstance().getInjector(ExtendedActivator.ORG_EXAMPLE_DOMAINMODEL_EXTENDED);
	}
	
}
