/**
 * generated by Xtext
 */
package org.example.domainmodel.ui.contentassist;

import org.example.domainmodel.ui.contentassist.AbstractExtendedProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ExtendedProposalProvider extends AbstractExtendedProposalProvider {
}
