/*
 * generated by Xtext
 */
package org.example.domainmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExtendedUiModule extends org.example.domainmodel.ui.AbstractExtendedUiModule {
	public ExtendedUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
