package gerador.compiled;

import org.eclipse.jet.JET2Context;
import org.eclipse.jet.JET2Template;
import org.eclipse.jet.JET2Writer;

public class _jet_templateNpm implements JET2Template {
    private final String templateFile;

    public _jet_templateNpm(String templateFile) {
        super();
        this.templateFile = templateFile;
    }

    private static final String NL = System.getProperty("line.separator"); //$NON-NLS-1$

    public void generate(final JET2Context context, final JET2Writer __out) {
        JET2Writer out = __out;
        out.pushTemplateFile(templateFile);
        out.write("// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/transition.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/alert.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/button.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/carousel.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/collapse.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/dropdown.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/modal.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/tooltip.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/popover.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/scrollspy.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/tab.js')");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("require('../../js/affix.js')");  //$NON-NLS-1$        
        out.popTemplateFile();
    }
}
